# Generated by Django 5.2.7 on 2025-11-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_securityalert_is_verified_securityalert_reported_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', max_length=10)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.CharField(default='Auto-Feed', max_length=100)),
                ('source_ip', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'ordering': ['-date_reported'],
            },
        ),
        migrations.DeleteModel(
            name='SecurityAlert',
        ),
    ]
